name: msc-paper-recommendation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy=1.26.4
  - scipy=1.16.0
  - scikit-learn=1.7.1
  - pandas
  - matplotlib
  - pip
  - pip:
      - torch==2.2.2
      - transformers==4.46.3
      - sentence-transformers==3.3.1
